spring:
  datasource:
    url: jdbc:mysql://localhost:3306/001
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: recruit
  config:
    import: classpath:jwt.properties

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换，如 user_name -> userName
  mapper-locations : classpath*:mapper/*.xml # 扫描mapper.xml文件

# 日志配置
logging:
  level:
    com.cat.recruit.mapper: debug


springdoc:
  swagger-ui:
    enabled: true

