spring:
  datasource:
    url: jdbc:mysql://localhost:3306/001
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: recruit
  config:
    import: classpath:jwt.properties


springdoc:
  swagger-ui:
    enabled: true

